### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/result-extra#7]
As per this: https://github.com/elm-community/Manifesto/issues/27.

**Comment by abadi199** [comment]
Same with `maybe-extra`, I'm gonna need help from owner to rename the repo, then I can publish the package.

**Comment by jvoigtlaender** [comment]
Done. What was the other repository where it's also needed? (I think you took over three, right?)

**Comment by abadi199** [comment]
Thanks!
I took over `elm-list-extra`, but that one is already published, so we're gonna need to mark the old one deprecated, and create a new repo with the new name.

**Comment by abadi199** [comment]
It's published! http://package.elm-lang.org/packages/elm-community/result-extra/1.0.0/
